/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogCadastroProduto.java
 *
 * Created on 12/02/2013, 20:21:09
 */
package br.edu.utfpr.cm.tsi.projetointegrador.gui.Produto;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Douglas Santiago
 */
public class JDialogCadastroProduto extends javax.swing.JDialog {
    private JDialogProdutoMenu pm = new JDialogProdutoMenu();
    private Conexao conexao = new Conexao();
//      private ConnectionManager con = new ConnectionManager();
    public static void main(String[] args) {

    }
    /** Creates new form JDialogCadastroProduto */
    public JDialogCadastroProduto() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        DescricaoText = new javax.swing.JFormattedTextField();
        NomeText = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QuantidadeText = new javax.swing.JFormattedTextField();
        CodigoText = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacoesText = new javax.swing.JTextArea();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNome.setText("NOME:");

        DescricaoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescricaoTextActionPerformed(evt);
            }
        });

        NomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setText("Cadastro Produto:");

        jLabel2.setText("Codigo:");

        QuantidadeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeTextActionPerformed(evt);
            }
        });

        CodigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade");

        jLabel7.setText("Observações:");

        ObservacoesText.setColumns(20);
        ObservacoesText.setRows(5);
        ObservacoesText.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ObservacoesTextAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(ObservacoesText);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel10.setText("Sistema Nadar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabelNome)
                            .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(357, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(610, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QuantidadeText, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(630, 630, 630))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(612, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(239, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addContainerGap(507, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuantidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void NomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextActionPerformed
//    NomeText.setText(p.getNome());
    // TODO add your handling code here:
}//GEN-LAST:event_NomeTextActionPerformed

private void DescricaoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescricaoTextActionPerformed
//   DescricaoText.setText(p.getDescricao());
    // TODO add your handling code here:
}//GEN-LAST:event_DescricaoTextActionPerformed

private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
    JOptionPane.showMessageDialog(rootPane, "Cancelado");
    dispose();
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonCancelarActionPerformed

private void CodigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTextActionPerformed
//   CodigoText.setText(p.getCodigo());
    // TODO add your handling code here:
}//GEN-LAST:event_CodigoTextActionPerformed

private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
     int n = JOptionPane.showConfirmDialog(rootPane, "Deseja Cadastar o Cliente: " + NomeText.getText());
        if(n==0){
    
    try {
            addProduto();
        } catch (Exception ex) {
            Logger.getLogger(JDialogCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    JOptionPane.showMessageDialog(rootPane, "Produto: " + NomeText.getText()+ " Cadastrado");
    int produtoId = Integer.parseInt(CodigoText.getText());
    dispose();
    new JDialogVisualizarProduto(produtoId).setVisible(true);
        }
        else if(n==2){
        dispose();
        }
}//GEN-LAST:event_jButtonConfirmarActionPerformed

private void QuantidadeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeTextActionPerformed
   
    // TODO add your handling code here:
}//GEN-LAST:event_QuantidadeTextActionPerformed
   
private void ObservacoesTextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ObservacoesTextAncestorAdded
    
    // TODO add your handling code here:
}//GEN-LAST:event_ObservacoesTextAncestorAdded
        
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CodigoText;
    private javax.swing.JFormattedTextField DescricaoText;
    private javax.swing.JFormattedTextField NomeText;
    private javax.swing.JTextArea ObservacoesText;
    private javax.swing.JFormattedTextField QuantidadeText;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    
   private void addProduto() throws Exception{
              
//            p.setCodigo(CodigoText.getText());
//            p.setNome(NomeText.getText());
//            p.setDescricao(DescricaoText.getText());
//            p.setQuantidade(QuantidadeText.getText());
//            p.setObservacoes( ObservacoesText.getText());
    
        Connection con = conexao.getConnection();
        
   
 try {
            String sql = "INSERT INTO produto(codigo, nome, descricao, quantidade, observacao) Values (?, ?, ?, ?, ?)";
            
            con.setAutoCommit(false);
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, CodigoText.getText());  
            pst.setString(2, NomeText.getText());  
            pst.setString(3, DescricaoText.getName());
            pst.setString(4, QuantidadeText.getText());  
            pst.setString(5, ObservacoesText.getText()); 
            pst.execute();
            
            con.commit();
            
        } catch (SQLException ex) {
            Logger.getLogger(JDialogCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            
        }
           
            
        
 
 
    }
   
   private void set(){
//   ObservacoesText.setText(p.getObservacoes());
   
   }


}


