/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogConsultaCliente.java
 *
 * Created on 24/02/2013, 20:21:10
 */
package br.edu.utfpr.cm.tsi.projetointegrador.gui.Cliente;
import br.edu.utfpr.cm.tsi.projetointegrador.coneccao.ConnectionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Daniele
 */
public class JDialogConsultaCliente extends javax.swing.JDialog {
    
    
    DefaultTableModel model;

    /** Creates new form JDialogConsultaCliente */
    public JDialogConsultaCliente() {
      super.setLocation(350, 180);
        initComponents();
       criaTabela();
    }

    //JDialogConsultaCliente() {
      //  throw new UnsupportedOperationException("Not yet implemented");
    //}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaClientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelSistemaNadar = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonOk = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Consulta Clientes"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsultaClientes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ConsultaClientes.setForeground(new java.awt.Color(0, 51, 204));
        ConsultaClientes.setText("Consulta Clientes:");
        getContentPane().add(ConsultaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 0));

        jTextMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, -1));

        jButtonPesquisar.setText("Pesquisar");
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabelSistemaNadar.setText("Sistema Nadar");
        getContentPane().add(jLabelSistemaNadar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabelMatricula.setText("Matrícula:");
        getContentPane().add(jLabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 290));

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 60, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButtonOkActionPerformed

private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jButtonExcluirActionPerformed

private void jTextMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMatriculaActionPerformed
// TODO add your handling code here:
    preencheTabela();
}//GEN-LAST:event_jTextMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogConsultaCliente dialog = new JDialogConsultaCliente();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConsultaClientes;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelSistemaNadar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextMatricula;
    // End of variables declaration//GEN-END:variables

    private void criaTabela() {
       // throw new UnsupportedOperationException("Not yet implemented");
        model = new DefaultTableModel(new String[]{"matricula","nome","CPF","endereço","bairro","telefone","cidade","email"},0){
              public boolean isCellEditable(int row ,int column){
                  return false;
              }
           };
        jTable1.setModel(model);
    }

    private void preencheTabela() {
       // throw new UnsupportedOperationException("Not yet implemented");
        
        model.setNumRows(0);
        
        Connection con=new ConnectionManager().Conexao();
        try{
            
            
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            
            String sql ="SELECT FROM cliente WHERE cliente.matricula. like  " +Integer.parseInt(jTextMatricula.getText())+";";
            
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet rs= pst.executeQuery();
            if(rs.next()){
                
                
                
            tableModel.addRow(new Object[]{rs.getInt("matricula"),rs.getString("nome"),rs.getString("CPF")
                    ,rs.getString("endereço"),rs.getString("bairro"),rs.getString("telefone"),rs.getString("cidade"),
                    rs.getString("email")});
               jTable1.setModel(tableModel);
               
                 con.close();
                 
            }
                    
            } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro busca banco");
                
            }
                   
            
        }
    }




